name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - 3.82
          - 4.2.1
          - 4.4.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install GPG keys
        run: |
          wget -q https://ftp.gnu.org/gnu/gnu-keyring.gpg
          gpg --import gnu-keyring.gpg

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: make --version
        env:
          MAKE_PRINT_BUILD_LOG: "yes"
