name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - 3.82
          - 4.2.1
          - 4.4.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install GPG keys
        run: gpg -v --keyserver keyserver.ubuntu.com --recv-keys 96B047156338B6D4 80CB727A20C79BB2

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: make --version
        env:
          MAKE_PRINT_BUILD_LOG: "yes"
