name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - 3.82
          - 4.2.1
          - 4.3
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: make --version
          gitref: ${{ steps.vars.outputs.short_ref }}
          version: ${{ matrix.version }}
        env:
          MAKE_PRINT_BUILD_LOG: "yes"
